language: python

matrix:
  include:
    # - os: osx
    - os: linux
      python: "3.5"
      compiler: gcc
    - os: linux
      python: "3.5"
      compiler: clang
    - os: linux
      python: "3.6"
      compiler: clang
    - os: linux
      python: "3.7-dev"
      compiler: clang

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - LIBPATH=$(python -c 'from distutils import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')
  - echo "$LIBPATH"
  - ls "$LIBPATH"
  - export LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  - cmake . -DCMAKE_FIND_DEBUG_MODE=1
