language: python

matrix:
  include:
    - os: osx
      compiler: clang
    - os: linux
      python: "3.5"
      compiler: gcc
    - os: linux
      python: "3.5"
      compiler: clang
    - os: linux
      python: "3.6"
      compiler: clang
    - os: linux
      python: "3.7-dev"
      compiler: clang
      env: TRAVIS_PYTHON_VERSION="3.7"

script:
  - echo "$TRAVIS_PYTHON_VERSION"
