language: python

matrix:
  include:
    # - os: osx
    - os: linux
      python: "3.5"
      compiler: gcc
    - os: linux
      python: "3.5"
      compiler: clang
    - os: linux
      python: "3.6"
      compiler: clang
    - os: linux
      python: "3.7-dev"
      compiler: clang

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - LIBPATH=$(which python | sed -e 's:\(.*\)/bin/.*:\1/lib:g')
  - echo "$LIBPATH"
  - ls "$LIBPATH/libpython*"
  - export LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  - cmake .
