language: python

matrix:
  include:
    - os: linux
      python: "3.5"
      compiler: gcc
    - os: linux
      python: "3.5"
      compiler: clang
    - os: osx
      python: "3.6"
      compiler: clang
    - os: linux
      python: "3.6"
      compiler: clang
    - os: linux
      python: "3.7-dev"
      compiler: clang

script:
  - echo "$TRAVIS_PYTHON_VERSION"
