language: cpp

matrix:
  include:
    - os: osx
    - os: linux
      compiler: gcc
      language: python
      python: "3.5"
    - os: linux
      compiler: clang
      language: python
      python: "3.5"
    - os: linux
      compiler: clang
      language: python
      python: "3.6"
    - os: linux
      compiler: clang
      language: python
      python: "3.7-dev"

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - pip install -U setuptools
  - python -c 'import setuptools; print(setuptools.__version__)'
  - cmake .
  - mkdir tmp
  - pushd tmp
  - popd
